# Generated by Django 4.0.6 on 2022-08-10 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_read',
        ),
        migrations.AddField(
            model_name='message',
            name='message_image',
            field=models.ImageField(blank=True, null=True, upload_to='messages_image'),
        ),
        migrations.AddField(
            model_name='message',
            name='users_read',
            field=models.ManyToManyField(blank=True, null=True, related_name='messages_read', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
